### PR TITLE
Unbridge fixes

### LINKED ISSUE #283: Unbridge from Discord side
I bridged a matrix room to a discord room using this public bridge: https://t2bot.io/discord/ ...and then left the Matrix room without unbridging.  I'm unable to get back in since it was invite-only, and I was the only one in it, so now it's just the Matrix bot in the room. I am concerned that messages sent in the discord room are still being bridged even though no one is in there.

Is there a way to unbridge from Discord? If not, this would be a valuable feature to have in case this happens.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #283, #336

### CODE REVIEW

File: src/channelsyncroniser.ts [hunk 1]
```diff
@@ -269,22 +283,24 @@ export class ChannelSyncroniser {
     private async handleChannelDeletionForRoom(
         channel: Discord.TextChannel,
         roomId: string,
-        entry: IRoomStoreEntry): Promise<void> {
+        entry: IRoomStoreEntry,
+        overrideOptions?: DiscordBridgeConfigChannelDeleteOptions): Promise<void> {
         log.info(`Deleting ${channel.id} from ${roomId}.`);
         const intent = await this.bridge.getIntent();
-        const options = this.config.channel.deleteOptions;
+        const options = overrideOptions || this.config.channel.deleteOptions;
```
Comment (Sorunome) [inline src/channelsyncroniser.ts]: Why not merge the objects properly? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

File: src/channelsyncroniser.ts [hunk 2]
```diff
@@ -269,22 +283,24 @@ export class ChannelSyncroniser {
...
         const plumbed = entry.remote!.get("plumbed");
+        // tslint:disable-next-line: no-any
```
Comment (Sorunome) [inline src/channelsyncroniser.ts]: stray tslint stuff?

File: src/provisioner.ts [hunk 3]
```diff
@@ -14,35 +14,56 @@ See the License for the specific language governing permissions and
...
+        const remoteRoom = roomsRes[0].remote as RemoteStoreRoom;
+        let roomsToUnbridge: string[] = [];
+        if (rId) {
+            roomsToUnbridge = [rId];
+        } else {
+            // Kill em all.
+            roomsToUnbridge = roomsRes.map((entry) => entry.matrix!.roomId);
+        }
+        await Promise.all(roomsToUnbridge.map( async (roomId) => {
+            return this.channelSync.OnUnbridge(channel, roomId).catch((err) => {
```
Comment (Sorunome) [inline src/provisioner.ts]: why not
```js
try {
    await this.channelSync.OnUnbridge(...);
} catch (err) {
    log.error(err);
}
```

File: src/util.ts [hunk 4]
```diff
@@ -35,7 +35,7 @@ export interface ICommandAction {
     description?: string;
     help?: string;
     params: string[];
-    permission?: PERMISSIONTYPES;
+    permission?: PERMISSIONTYPES | PERMISSIONTYPES[];
```
Comment (Sorunome) [inline src/util.ts]: eeeer, wouldn't it be better to change `type PERMISSIONTYPES = any | any[]; // tslint:disable-line no-any` instead?

File: src/channelsyncroniser.ts (hunk 1 above)
Comment (Half-Shot) [reply src/channelsyncroniser.ts]: The intention of overrideOptions is to literally force a certain config rather than overlay it across.

File: src/util.ts (hunk 4 above)
Comment (Half-Shot) [reply src/util.ts]: oh yeah, maybe
