### PR TITLE
Update yarn.lock and fix Docker builds

### LINKED ISSUE #824: `yarn.lock` seems out of sync for v2.0.0
Installation of release v2.0.0 using the strict version requirements from the
lock file fails:

```log
❯ nix log /nix/store/414s3b1p2krfsnn9hhv9yk08xkxw390c-matrix-appservice-discord-modules-2.0.0.drv
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
yarn config v1.22.19
success Set "yarn-offline-mirror" to "/nix/store/gxmyj7wx1vzaifqjsjby3kdmfqnklni2-offline".
Done in 0.02s.
yarn install v1.22.19
[1/4] Resolving packages...
error Couldn't find any versions for "@types/node" that matches "^14" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This is problematic for some distribution packages like on nixpkgs.

It seems to be due to `yarn.lock` being out of sync with `package.json`.
It could be a good idea to check that through the CI, in particular for tagged
releases.

### PR DESCRIPTION
**Pull request by jaller94**
* Fixes #824 
* Part of #822 – given that @Half-Shot publishes the Docker image.
* Supersedes #798
* Upgrades `matrix-appservice-bridge` to v5.0.0 which requires Node.js 16, 17 or 18

### CODE REVIEW

**Comment by jaller94** [comment]
With [3e491ca](https://github.com/matrix-org/matrix-appservice-discord/pull/825/commits/3e491ca7b3aed2e58a14c18027a4f14bbc29658a) this is now a breaking change that requires a new major version.

Because of the library `matrix-appservice-bridge` v5.0.0 the supported Node.js versions are 16 and 18.

File: changelog.d/825.misc [hunk 1]
```diff
@@ -0,0 +1 @@
+Require Node.js 16, 17 or 18 to run. Update yarn.lock and fix Docker builds.
```
Comment (Half-Shot) [inline changelog.d/825.misc]:
```suggestion
Minimum required Node.js version is now 16.
```

Comment (Half-Shot) [reply changelog.d/825.misc]: This also needs to be a `.removal` to indicate that it's a breaking change.

**Review by Half-Shot — APPROVED** [review]
I don't think we need to be explicit about all the versions we support, 16 is the headline. Otherwise, lgtm.
