### PR TITLE
Fix webhook usersync issues

### LINKED ISSUE #534: webhook avatar
investigate if webhook avatars don't bridge correctly, didn't for one instance here

### PR DESCRIPTION
**Pull request by Sorunome**
fixes #534

### CODE REVIEW

File: src/usersyncroniser.ts [hunk 1]
```diff
@@ -233,10 +233,10 @@ export class UserSyncroniser {
         let mxidExtra = "";
         if (webhookID) {
             // no need to escape as this mxid is only used to create an intent
-            mxidExtra = `_${new MatrixUser(`@${webhookID}`).localpart}`;
+            mxidExtra = `_${new MatrixUser(`@${discordUser.username}`).localpart}`;
```
Comment (Half-Shot) [inline src/usersyncroniser.ts]: So what was wrong with webhookID, it's not clear to me?

File: src/usersyncroniser.ts [hunk 2]
```diff
@@ -233,10 +233,10 @@ export class UserSyncroniser {
         let mxidExtra = "";
         if (webhookID) {
```
Comment (Half-Shot) [inline src/usersyncroniser.ts]: if we are no longer using the ID, can this be a boolean instead?

File: src/usersyncroniser.ts (hunk 1 above)
Comment (Sorunome) [reply src/usersyncroniser.ts]: the problem was that the same webhook can have different names and we don't want username changes constantly. So we fixed that by appending the name to the ID. Only, somehow here, the webhook id instead of the name was appended, which caused problems

Comment (Half-Shot) [reply src/usersyncroniser.ts]: Hm, okay. Can this be commented above?

Comment (Sorunome) [reply src/usersyncroniser.ts]: done

File: src/usersyncroniser.ts (hunk 2 above)
Comment (Sorunome) [reply src/usersyncroniser.ts]: done

**Comment by Half-Shot** [comment]
I guess this is fine :smile:
