### PR TITLE
Use debian slim for docker builds

### LINKED ISSUE #827: Docker image doesn't start since recent changes.
**Describe the bug**
Since the recent changes to git I assume it is #825. The docker image doesn't start anymore. This also applies to the docker image at ghcr.io/matrix-org/matrix-appservice-discord:develop

**To Reproduce**
1. Compile the docker image or use ghcr.io/matrix-org/matrix-appservice-discord:develop
2. Start the image
3. Check logs

**Expected behavior**
The Docker image should start without any errors.

**Logs**
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /node_modules/@matrix-org/matrix-sdk-crypto-nodejs/matrix-sdk-crypto.linux-x64-musl.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:159:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Additional context**
It worked fine before these new commits.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #827 

Matrix-appservice-bridge 5.0.0 brought in new changes (matrix-bot-sdk) which relies on compiled crypto modules. These modules do not appear to work properly on alpine.

```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /node_modules/@matrix-org/matrix-sdk-crypto-nodejs/matrix-sdk-crypto.linux-x64-musl.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/node_modules/@matrix-org/matrix-sdk-crypto-nodejs/index.js:159:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Prior experience has taught me that alpine and native rust modules tend not to blend too well, so I'm going to say we just use debian-slim for our images. We do this for the Slack/IRC/Hookshot bridges already.

### CODE REVIEW

File: changelog.d/828.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix docker instances not starting due to being unable to load a dynamic library.
```
Comment (jaller94) [inline changelog.d/828.bugfix]: I think that changelog messages should relate to the latest stable release.
This wasn't broken in the latest stable release, but got introduced in #825.

**Review by justinbot — APPROVED** [review]
